<svelte:head>
    <title>Agrimatco | Stručni savjeti | Kemijski sastav gnojiva</title>
</svelte:head>

<script>
    import Table from '../../../components/Table.svelte';
</script>

<style>
    .container-large {
        max-width: unset;
    }
    .container-large :global(table) {
        margin: auto;
        width: auto !important;
    }
</style>

<section class="section">
    <div class="container">
        <nav><small><a  href="/strucni-savjeti">Stručni savjeti</a> > Kemijski sastav gnojiva</small></nav>
        <h1>Kemijski sastav gnojiva</h1>
    </div>

    <div class="container container-large">
        <Table>
            <tr>
                <th>Formulacija</th>
                <th>N-total</th>
                <th>N-NO<sub>3</sub></th>
                <th>N-NH<sub>4</sub></th>
                <th>N-NH<sub>2</sub></th>
                <th>P<sub>2</sub>O<sub>5</sub></th>
                <th>K<sub>2</sub>O</th>
                <th>MGO</th>
                <th>CA</th>
                <th>S</th>
                <th>Fe</th>
                <th>Zn</th>
                <th>Cu</th>
                <th>B</th>
                <th>Mn</th>
                <th>Mo</th>
                <th><sup>*</sup>LAK</th>
                <th><sup>*</sup>OE</th>
            </tr>
            <tr>
                <td><b>Novalon 20-20-20 <sub>+</sub> TE</b></td>
                <td>20</td>
                <td>5,3</td>
                <td>3,4</td>
                <td>11,3</td>
                <td>20</td>
                <td>20</td>
                <td></td>
                <td></td>
                <td></td>
                <td>0,08</td>
                <td>0,03</td>
                <td>0,015</td>
                <td>0,015</td>
                <td>0,03</td>
                <td>0,002</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Novalon 12-48-6<sub>+</sub>TE</b></td>
                <td>12</td>
                <td>1,5</td>
                <td>10,5</td>
                <td></td>
                <td>48</td>
                <td>6</td>
                <td></td>
                <td></td>
                <td></td>
                <td>0,08</td>
                <td>0,03</td>
                <td>0,015</td>
                <td>0,015</td>
                <td>0,03</td>
                <td>0,002</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Novalon 15-5-35<sub>+</sub>TE</b></td>
                <td>15</td>
                <td>11,5</td>
                <td>3,5</td>
                <td></td>
                <td>5</td>
                <td>35</td>
                <td></td>
                <td></td>
                <td></td>
                <td>0,08</td>
                <td>0,03</td>
                <td>0,015</td>
                <td>0,015</td>
                <td>0,03</td>
                <td>0,002</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Novalon 6-12-36<sub>+</sub>3MGO<sub>+</sub>TE</b></td>
                <td>6</td>
                <td>4,5</td>
                <td>1,5</td>
                <td></td>
                <td>12</td>
                <td>36</td>
                <td>3</td>
                <td></td>
                <td></td>
                <td>0,08</td>
                <td>0,03</td>
                <td>0,015</td>
                <td>0,015</td>
                <td>0,03</td>
                <td>0,002</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Novalon 19-6-20<sub>+</sub>2MgO<sub>+</sub>TE</b></td>
                <td>19</td>
                <td>10,9</td>
                <td>8,1</td>
                <td></td>
                <td>6</td>
                <td>20</td>
                <td>2</td>
                <td></td>
                <td></td>
                <td>0,08</td>
                <td>0,03</td>
                <td>0,015</td>
                <td>0,015</td>
                <td>0,03</td>
                <td>0,002</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Novalon 0-5-35<sub>+</sub>4,5 MgO<sub>+</sub>TE</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>5</td>
                <td>35</td>
                <td>4,5</td>
                <td></td>
                <td>13</td>
                <td>0,05</td>
                <td>0,02</td>
                <td>0,01</td>
                <td>0,01</td>
                <td>0,02</td>
                <td>0,001</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Keymag 10-0-40<sub>+</sub>2MgO</b></td>
                <td>10</td>
                <td>10</td>
                <td></td>
                <td></td>
                <td></td>
                <td>40</td>
                <td>2</td>
                <td></td>
                <td>3,7</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Amcopaste 13-13-13</b> m/m</td>
                <td>13</td>
                <td>3,9</td>
                <td>3</td>
                <td>6,1</td>
                <td>13</td>
                <td>13</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Amcopaste 12-30-6        m/m</b></td>
                <td>12</td>
                <td></td>
                <td>1</td>
                <td>11</td>
                <td>30</td>
                <td>6</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Amcopaste 8-11-28        m/m</b></td>
                <td>8</td>
                <td>4</td>
                <td></td>
                <td></td>
                <td>11</td>
                <td>28</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Multi N</b></td>
                <td>40</td>
                <td>11</td>
                <td>11</td>
                <td>18</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>AMCO Potato</b></td>
                <td>14</td>
                <td>4</td>
                <td>5,3</td>
                <td>4,7</td>
                <td>25</td>
                <td>13</td>
                <td>3,5</td>
                <td></td>
                <td>12,5</td>
                <td></td>
                <td>1,8</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Bioplex  (stimulator rasta)</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>112,5</td>
            </tr>
            <tr>
                <td><b>Rootex</b></td>
                <td>6</td>
                <td></td>
                <td>6</td>
                <td></td>
                <td>46</td>
                <td>6</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>18,5</td>
            </tr>
            <tr>
                <td><b>Trazex</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>6</td>
                <td>6</td>
                <td>2</td>
                <td>2</td>
                <td>6</td>
                <td></td>
                <td>3</td>
                <td>2</td>
            </tr>
            <tr>
                <td><b>Kelatex B</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>17</td>
                <td></td>
                <td></td>
                <td>3</td>
                <td>2</td>
            </tr>
            <tr>
                <td><b>Ketalex Fe</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>18</td>
                <td>2</td>
                <td></td>
                <td></td>
                <td>1</td>
                <td></td>
                <td>3</td>
                <td>2</td>
            </tr>
            <tr>
                <td><b>Ketalex Zn</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>25</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
                <td>2</td>
            </tr>
            <tr>
                <td><b>Tropicel</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>10</td>
                <td></td>
                <td>10</td>
                <td></td>
                <td>0,5</td>
                <td>3</td>
                <td>2</td>
            </tr>
            <tr>
                <td><b>Calcium Mainstay</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>H - 85</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Agrofol 650</b></td>
                <td>20</td>
                <td></td>
                <td>14,6</td>
                <td>5,4</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>78,5</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Agrofol 390</b></td>
                <td>12,7</td>
                <td></td>
                <td>12,7</td>
                <td></td>
                <td>12,7</td>
                <td>12,7</td>
                <td></td>
                <td></td>
                <td></td>
                <td>0,1</td>
                <td>0,08</td>
                <td></td>
                <td>0,1</td>
                <td>0,08</td>
                <td>0,025</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Kalex</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>42</td>
                <td>28</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Kalex Cu</b></td>
                <td>4,3</td>
                <td></td>
                <td>4,3</td>
                <td></td>
                <td>30</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>0,17</td>
                <td>5,8</td>
                <td>0,19</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td><b>Boramide</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>15</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td colspan="18" style="text-align: right;">*LAK - L-aminokiseline, *OE - organski ekstrakti</td>
            </tr>
        </Table>
    </div>
</section>
