<svelte:head>
    <title>Agrimatco | Stručni savjeti | Orijentacione granične EC vrijednosti</title>
</svelte:head>

<script>
    import Table from '../../../components/Table.svelte';
</script>

<section class="section">
    <div class="container">
        <nav><small><a  href="/strucni-savjeti">Stručni savjeti</a> > Orijentacione granične EC vrijednosti</small></nav>
        <h1>Orijentacione granične EC vrijednosti</h1>
        <p>Orijentacione granične EC vrijednosti (dS/m) u uzgoju povrtnih vrsta u tlu i EC vrijednosti koje rezultiraju smanjenjem prinosa.</p>
        <Table>
            <tr>
                <th rowspan="2"></th><th rowspan="2">Granična EC vrijednost</th><th colspan="3">Smanjenje prinosa</th>
            </tr>
            <tr>
                <th>10%</th>
                <th>25%</th>
                <th>50%</th>
            </tr>
            <tr>
                <td>Šparoga</td>
                <td>5,0</td>
                <td>8,0</td>
                <td>11,0</td>
                <td>13,0</td>
            </tr>
            <tr>
                <td>Grah</td>
                <td>1,0</td>
                <td>1,5</td>
                <td>2,3</td>
                <td>3,6</td>
            </tr>
            <tr>
                <td>Grašak</td>
                <td>0,9</td>
                <td>2,0</td>
                <td>3,7</td>
                <td>6,5</td>
            </tr>
            <tr>
                <td>Luk</td>
                <td>1,2</td>
                <td>1,8</td>
                <td>2,8</td>
                <td>4,3</td>
            </tr>
            <tr>
                <td>Mrkva</td>
                <td>1,0</td>
                <td>1,7</td>
                <td>2,8</td>
                <td>4,6</td>
            </tr>
            <tr>
                <td>Krumpir</td>
                <td>1,7</td>
                <td>2,5</td>
                <td>3,8</td>
                <td>5,9</td>
            </tr>
            <tr>
                <td>Celer</td>
                <td>1,8</td>
                <td>3,5</td>
                <td>5,8</td>
                <td>10,1</td>
            </tr>
            <tr>
                <td>Krastavac</td>
                <td>2,5</td>
                <td>3,3</td>
                <td>4,4</td>
                <td>6,3</td>
            </tr>
            <tr>
                <td>Tikvica</td>
                <td>3,9</td>
                <td>4,9</td>
                <td>5,9</td>
                <td>7,9</td>
            </tr>
            <tr>
                <td>Rajčica</td>
                <td>2,5</td>
                <td>3,5</td>
                <td>5,0</td>
                <td>7,6</td>
            </tr>
            <tr>
                <td>Paprika</td>
                <td>1,3</td>
                <td>2,2</td>
                <td>3,3</td>
                <td>5,1</td>
            </tr>
            <tr>
                <td>Lubenica</td>
                <td>2,0</td>
                <td>2,5</td>
                <td>3,5</td>
                <td>4,5</td>
            </tr>
            <tr>
                <td>Salata</td>
                <td>1,3</td>
                <td>2,1</td>
                <td>3,2</td>
                <td>5,2</td>
            </tr>
            <tr>
                <td>Špinat</td>
                <td>3,7</td>
                <td>5,5</td>
                <td>7,0</td>
                <td>8,0</td>
            </tr>
            <tr>
                <td>Kupus</td>
                <td>1,8</td>
                <td>2,8</td>
                <td>4,4</td>
                <td>7,0</td>
            </tr>
            <tr>
                <td>Brokula</td>
                <td>2,7</td>
                <td>3,5</td>
                <td>5,5</td>
                <td>8,2</td>
            </tr>
            <tr>
                <td>Cvjetača</td>
                <td>2,7</td>
                <td>3,5</td>
                <td>4,7</td>
                <td>5,8</td>
            </tr>
        </Table>
    </div>
</section>
